version: "3.8"

services:
  backend:
    build: .
    image: arancia-backend:latest
    restart: always
    env_file: .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
    networks:
      - dokploy-network

volumes:
  uploads:

networks:
  dokploy-network:
    external: true
    name: dokploy-network
